import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./provider";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FundMEKGP",
  description: "Generated by create next app",
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
      <AuthProvider>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </AuthProvider>
        
        </body>
    </html>
  );
}
